version: "3"

services:
  traefik:
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - ./certs/wildcard.soc.imerir.key:/traefik.key:ro
      - ./certs/wildcard.soc.imerir.cert:/traefik.crt:ro
      - ./data/log:/var/log/
    restart: always
    labels:
      - "traefik.backend=traefikui"
      - "traefik.frontend.rule=Host:traefik.soc.imerir"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_default"
    networks:
      default:
        aliases:
         - reload.soc.imerir
         - auth.soc.imerir

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 10.255.1.0/28
